# Setup
setup: multi_task

# Database
train_db_name: PASCALContext
val_db_name: PASCALContext 
trBatch: 2
valBatch: 2
nworkers: 2

# Optimizer and scheduler
epochs: 100
optimizer: adamw
optimizer_kwargs:
   lr: 0.00005
   weight_decay: 0.0001
scheduler: poly

# Model
model: SingleTaskModelSaliency_PASCAL #MultiTask_Former
backbone: swim_transformer2
backbone_kwargs:
   pretrained: True
   dilated: False
head: deeplab2

eval_final_10_epochs_only : True
gradient_surgery: True

# Tasks
task_dictionary:
   include_semseg: False
   include_human_parts: False
   include_sal: True

# Loss kwargs
loss_kwargs:
   loss_scheme: static
   loss_weights:
       sal: 1.0